### ISSUE TITLE
Formula only successfully building from HEAD

### ISSUE THREAD

**Issue by dmey** [WRF-CMake/homebrew-wrf#3]
The current formula is based on WRF-CMake 4.0.3 where clang was not supported.
The current formula can only be successfully be built using the latest commits in wrf-cmake branch. To build from the latest commit in wrf-cmake, users can pass the `--HEAD` flag when building. I will update the docs accordingly for now until we release 4.1.0

**Comment by zbeekman** [comment]
My proposed alternate PR, #4, resolves this by defaulting to a more recent commit sha as the version.

**Comment by letmaik** [comment]
I would prefer @zbeekman's PR, but let's figure out anyway why @dmey is having problems with compiler choice. I would have expected that brew deals with this, but clearly it's not fully working. If we can't resolve this then we need to at least give advice on how to use the `--cc` etc arguments.

**Comment by dmey** [comment]
Likewise. I would suggest closing this one as it's fixed in #4.
